# config.yaml
base_name: "dorado_7302_day3_PromethION_no_tag_yes_rejection"
day0_base_name: "dorado_7302_day0_PromethION_no_tag_yes_rejection"
anchor_set: "telomerase_shutoff_anchors"
bam_dir: "samples_dorado_basecalled"
strain: "7302"

# BLAST parameter
min_raw_gapped_score: 5000

# Paths to references
references:
  anchors: "references/telomerase_shutoff_anchors.fasta"
  adapters: "references/nanopore_sqk-slk114_adapter_sequence_truncated.txt"
  probe: "references/y_prime_probe.fasta"

  # Strain-specific (used by recombination steps 10-12)
  y_prime_lib: "references/extracted_yprimes_{strain}.fasta"
  # Override with curated library for testing (comment out to use extracted version)
  y_prime_lib_override: "references/7302_features/repeatmasker_7302_all_y_primes.fasta"
  spacer_lib_dir: "references/pairings_for_spacers/{strain}_pairings"
  x_element_lib_dir: "references/pairings_for_x_element_ends/{strain}_pairings"
